@ECHO off

PUSHD %~dp0

SET CMAKE=cmake
SET CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
SET CMAKE_BINARY_DIR=build_2017

MKDIR %CMAKE_BINARY_DIR% 2>NUL
PUSHD %CMAKE_BINARY_DIR%
%CMAKE% -G %CMAKE_GENERATOR% -Wno-dev "%~dp0"
POPD

POPD

